/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ss_local.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ss_local.pb-c.h"
void   ssproxy_request__init
                     (SSProxyRequest         *message)
{
  static const SSProxyRequest init_value = SSPROXY_REQUEST__INIT;
  *message = init_value;
}
size_t ssproxy_request__get_packed_size
                     (const SSProxyRequest *message)
{
  assert(message->base.descriptor == &ssproxy_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ssproxy_request__pack
                     (const SSProxyRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ssproxy_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ssproxy_request__pack_to_buffer
                     (const SSProxyRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ssproxy_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SSProxyRequest *
       ssproxy_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SSProxyRequest *)
     protobuf_c_message_unpack (&ssproxy_request__descriptor,
                                allocator, len, data);
}
void   ssproxy_request__free_unpacked
                     (SSProxyRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ssproxy_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ssproxy_result__init
                     (SSProxyResult         *message)
{
  static const SSProxyResult init_value = SSPROXY_RESULT__INIT;
  *message = init_value;
}
size_t ssproxy_result__get_packed_size
                     (const SSProxyResult *message)
{
  assert(message->base.descriptor == &ssproxy_result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ssproxy_result__pack
                     (const SSProxyResult *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ssproxy_result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ssproxy_result__pack_to_buffer
                     (const SSProxyResult *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ssproxy_result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SSProxyResult *
       ssproxy_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SSProxyResult *)
     protobuf_c_message_unpack (&ssproxy_result__descriptor,
                                allocator, len, data);
}
void   ssproxy_result__free_unpacked
                     (SSProxyResult *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ssproxy_result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ssproxy_request__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SSProxyRequest, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "speed_test",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(SSProxyRequest, speed_test),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "from_obfs",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(SSProxyRequest, from_obfs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ssproxy_request__field_indices_by_name[] = {
  2,   /* field[2] = from_obfs */
  0,   /* field[0] = name */
  1,   /* field[1] = speed_test */
};
static const ProtobufCIntRange ssproxy_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ssproxy_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SSProxyRequest",
  "SSProxyRequest",
  "SSProxyRequest",
  "",
  sizeof(SSProxyRequest),
  3,
  ssproxy_request__field_descriptors,
  ssproxy_request__field_indices_by_name,
  1,  ssproxy_request__number_ranges,
  (ProtobufCMessageInit) ssproxy_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ssproxy_result__field_descriptors[7] =
{
  {
    "success",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(SSProxyResult, success),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "host",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SSProxyResult, host),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SSProxyResult, port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "method",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SSProxyResult, method),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "password",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SSProxyResult, password),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "obfs",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SSProxyResult, obfs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "obfshost",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SSProxyResult, obfshost),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ssproxy_result__field_indices_by_name[] = {
  1,   /* field[1] = host */
  3,   /* field[3] = method */
  5,   /* field[5] = obfs */
  6,   /* field[6] = obfshost */
  4,   /* field[4] = password */
  2,   /* field[2] = port */
  0,   /* field[0] = success */
};
static const ProtobufCIntRange ssproxy_result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor ssproxy_result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SSProxyResult",
  "SSProxyResult",
  "SSProxyResult",
  "",
  sizeof(SSProxyResult),
  7,
  ssproxy_result__field_descriptors,
  ssproxy_result__field_indices_by_name,
  1,  ssproxy_result__number_ranges,
  (ProtobufCMessageInit) ssproxy_result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
