/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ss_local.proto */

#ifndef PROTOBUF_C_ss_5flocal_2eproto__INCLUDED
#define PROTOBUF_C_ss_5flocal_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _SSProxyRequest SSProxyRequest;
typedef struct _SSProxyResult SSProxyResult;


/* --- enums --- */


/* --- messages --- */

struct  _SSProxyRequest
{
  ProtobufCMessage base;
  char *name;
  protobuf_c_boolean speed_test;
  protobuf_c_boolean from_obfs;
};
#define SSPROXY_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ssproxy_request__descriptor) \
    , NULL, 0, 0 }


struct  _SSProxyResult
{
  ProtobufCMessage base;
  protobuf_c_boolean success;
  char *host;
  char *port;
  char *method;
  char *password;
  char *obfs;
  char *obfshost;
};
#define SSPROXY_RESULT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ssproxy_result__descriptor) \
    , 0, NULL, NULL, NULL, NULL, NULL, NULL }


/* SSProxyRequest methods */
void   ssproxy_request__init
                     (SSProxyRequest         *message);
size_t ssproxy_request__get_packed_size
                     (const SSProxyRequest   *message);
size_t ssproxy_request__pack
                     (const SSProxyRequest   *message,
                      uint8_t             *out);
size_t ssproxy_request__pack_to_buffer
                     (const SSProxyRequest   *message,
                      ProtobufCBuffer     *buffer);
SSProxyRequest *
       ssproxy_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ssproxy_request__free_unpacked
                     (SSProxyRequest *message,
                      ProtobufCAllocator *allocator);
/* SSProxyResult methods */
void   ssproxy_result__init
                     (SSProxyResult         *message);
size_t ssproxy_result__get_packed_size
                     (const SSProxyResult   *message);
size_t ssproxy_result__pack
                     (const SSProxyResult   *message,
                      uint8_t             *out);
size_t ssproxy_result__pack_to_buffer
                     (const SSProxyResult   *message,
                      ProtobufCBuffer     *buffer);
SSProxyResult *
       ssproxy_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ssproxy_result__free_unpacked
                     (SSProxyResult *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*SSProxyRequest_Closure)
                 (const SSProxyRequest *message,
                  void *closure_data);
typedef void (*SSProxyResult_Closure)
                 (const SSProxyResult *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor ssproxy_request__descriptor;
extern const ProtobufCMessageDescriptor ssproxy_result__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_ss_5flocal_2eproto__INCLUDED */
